import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, AlertCircle } from 'lucide-react';
import { useReport } from '../../hooks/useReport';
import { ReportSkeleton } from '../../components/shared/Skeleton';
import ExportMenu from '../../components/shared/ExportMenu';
import VersionHistoryDropdown from '../../components/shared/VersionHistoryDropdown';
import ReportSummaryBanner from '../../components/report/ReportSummaryBanner';
import InvestmentAnalysisChart from '../../components/report/InvestmentAnalysisChart';
import EmployeeTable from '../../components/report/EmployeeTable';
import SchemeCard from '../../components/report/SchemeCard';
import LoanGuidanceCard from '../../components/report/LoanGuidanceCard';
import RiskAccordion from '../../components/report/RiskAccordion';
import ProsConsGrid from '../../components/report/ProsConsGrid';
import ActionChecklist from '../../components/report/ActionChecklist';
import NextStepsTimeline from '../../components/report/NextStepsTimeline';

export default function ReportPage() {
  const { reportId } = useParams<{ reportId: string }>();
  const { data: report, isLoading, isError } = useReport(reportId ?? '');

  if (isLoading) return <ReportSkeleton />;

  if (isError || !report) {
    return (
      <div className="card p-12 text-center">
        <AlertCircle className="w-10 h-10 text-red-400 mx-auto mb-3" />
        <h2 className="text-lg font-semibold text-slate-900 mb-1">Report not found</h2>
        <p className="text-slate-500 text-sm mb-5">This report may have been deleted or the link is invalid.</p>
        <Link to="/dashboard" className="btn-primary inline-flex">Back to Dashboard</Link>
      </div>
    );
  }

  const rj = report.reportJson;
  const businessId = typeof report.businessId === 'object'
    ? report.businessId._id
    : report.businessId;
  const businessName = typeof report.businessId === 'object'
    ? report.businessId.businessName
    : 'Business Report';

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Top bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 no-print">
        <div className="flex items-center gap-2">
          <Link to={`/business/${businessId}`} className="btn-secondary p-2">
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <VersionHistoryDropdown businessId={businessId} currentReportId={report._id} />
        </div>
        <ExportMenu reportId={report._id} businessId={businessId} />
      </div>

      {/* 1 — Executive Summary */}
      <ReportSummaryBanner
        businessName={businessName}
        summary={rj?.executive_summary ?? ''}
        viabilityScore={rj?.pros_and_cons?.overall_viability_score}
        overallRisk={rj?.risks?.overall_risk_rating}
        version={report.version}
        createdAt={report.createdAt}
      />

      {/* 2 — Investment Analysis */}
      {rj?.investment_analysis && (
        <InvestmentAnalysisChart data={rj.investment_analysis} />
      )}

      {/* 3 — Employee Requirements */}
      {rj?.employee_requirement && (
        <EmployeeTable data={rj.employee_requirement} />
      )}

      {/* 4 — Government Schemes */}
      {rj?.government_schemes && (
        <SchemeCard data={rj.government_schemes} />
      )}

      {/* 5 — Bank Loan Guidance */}
      {rj?.bank_loan_guidance && (
        <LoanGuidanceCard data={rj.bank_loan_guidance} />
      )}

      {/* 6 — Risks */}
      {rj?.risks && (
        <RiskAccordion data={rj.risks} />
      )}

      {/* 7 — Pros & Cons */}
      {rj?.pros_and_cons && (
        <ProsConsGrid data={rj.pros_and_cons} />
      )}

      {/* 8 — Action Plan */}
      {rj?.action_plan && (
        <ActionChecklist data={rj.action_plan} />
      )}

      {/* 9 — Next Steps */}
      {rj?.next_steps && (
        <NextStepsTimeline steps={rj.next_steps} />
      )}

      {/* Disclaimer footer */}
      <div className="card p-4 text-xs text-slate-400 text-center leading-relaxed">
        This report was generated by AI for informational purposes only. It does not constitute financial, legal, or tax advice.
        Always consult a qualified Chartered Accountant, lawyer, or banking advisor before making business decisions.
      </div>
    </div>
  );
}
